import { SUPABASE_URL,SUPABASE_ANON_KEY,STORAGE_BUCKET,DEMO_MODE } from './config.js';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=DEMO_MODE?null:createClient(SUPABASE_URL,SUPABASE_ANON_KEY);const $=s=>document.querySelector(s);let session=null;let records=[];
const status=m=>$('#status').textContent=m||'';
function showDash(){ $('#loginView').classList.add('hidden');$('#dashboard').classList.remove('hidden');$('#logout').classList.remove('hidden');load(); }
async function load(){const {data,error}=await supabase.from('projects').select('*').order('created_at',{ascending:false});if(error){status(error.message);return}records=data||[];$('#projectList').innerHTML=records.map(p=>`<article class="glass rounded-2xl p-5"><div class="flex justify-between gap-4"><div><p class="text-[10px] uppercase tracking-[.2em]" style="color:${p.color}">UB. ${p.division}</p><h3 class="text-xl font-black mt-1">${escape(p.title)}</h3><p class="text-sm text-white/40 mt-2">${p.year||''} · ${p.published?'Publicado':'Oculto'}</p></div><div class="flex gap-2"><button data-edit="${p.id}" class="rounded-lg border border-white/10 px-3 py-2 text-xs">Editar</button><button data-delete="${p.id}" class="rounded-lg border border-red-400/20 text-red-300 px-3 py-2 text-xs">Excluir</button></div></div></article>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete));}
function escape(v=''){return v.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function openForm(p){$('#formWrap').classList.remove('hidden');$('#projectId').value=p?.id||'';$('#title').value=p?.title||'';$('#year').value=p?.year||'';$('#division').value=p?.division||'pictures';$('#color').value=p?.color||'#18bdf2';$('#description').value=p?.description||'';$('#featured').checked=!!p?.featured;$('#published').checked=p?p.published!==false:true;$('#currentImage').textContent=p?.image_url?'Arte atual: armazenada no Storage':'';window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});}
function edit(id){openForm(records.find(p=>p.id===id))}async function remove(id){if(!confirm('Excluir este projeto?'))return;const {error}=await supabase.from('projects').delete().eq('id',id);if(error)status(error.message);else load()}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();if(DEMO_MODE){status('Configure o Supabase para ativar o painel.');return}const {data,error}=await supabase.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error){status(error.message);return}session=data.session;showDash()});$('#logout').onclick=async()=>{await supabase.auth.signOut();location.reload()};$('#newBtn').onclick=()=>openForm();['cancelBtn','cancelBtn2'].forEach(id=>$('#'+id).onclick=()=>$('#formWrap').classList.add('hidden'));
$('#projectForm').addEventListener('submit',async e=>{e.preventDefault();if(!session){status('Sessão expirada.');return}const id=$('#projectId').value;let imageUrl=records.find(p=>p.id===id)?.image_url||null;const file=$('#imageFile').files[0];if(file){const ext=file.name.split('.').pop().toLowerCase();const path=`${crypto.randomUUID()}.${ext}`;const up=await supabase.storage.from(STORAGE_BUCKET).upload(path,file,{upsert:false,contentType:file.type});if(up.error){status(up.error.message);return}imageUrl=supabase.storage.from(STORAGE_BUCKET).getPublicUrl(path).data.publicUrl}
const payload={title:$('#title').value.trim(),year:Number($('#year').value)||null,division:$('#division').value,color:$('#color').value,description:$('#description').value.trim(),image_url:imageUrl,featured:$('#featured').checked,published:$('#published').checked};let res=id?await supabase.from('projects').update(payload).eq('id',id):await supabase.from('projects').insert(payload);if(res.error){status(res.error.message);return}$('#formWrap').classList.add('hidden');status('Salvo com sucesso.');load()});
if(!DEMO_MODE){supabase.auth.getSession().then(({data})=>{session=data.session;if(session)showDash()});supabase.auth.onAuthStateChange((_e,s)=>{session=s})}else status('Modo demonstração: o site público funciona, mas o Studio Manager precisa de Supabase.');
