import { DEMO_MODE, SUPABASE_URL, SUPABASE_ANON_KEY } from './config.js';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const supabase = DEMO_MODE ? null : createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
const demoProjects = [
  {id:'demo-1',title:'The Last Horizon',division:'pictures',year:2026,color:'#18bdf2',image:'',description:'Um longa em desenvolvimento.'},
  {id:'demo-2',title:'Dreamworld',division:'animation',year:2026,color:'#ff2525',image:'',description:'Uma nova aventura animada.'},
  {id:'demo-3',title:'Untitled Project',division:'pictures',year:2027,color:'#6d7cff',image:'',description:'Em produção.'}
];
const tickerItems=[['UNIVERSAL BROTHERS ENTERTAINMENT','white'],['UB. ANIMATION','red'],['UB. PICTURES','cyan']];
let projects=[];

const $=s=>document.querySelector(s);
function renderTicker(){const el=$('#ticker');let i=0;const paint=()=>{const [txt,c]=tickerItems[i];el.innerHTML=c==='red'?`<span>UB.</span> <span class="text-red-500">ANIMATION</span>`:c==='cyan'?`<span>UB.</span> <span class="text-cyan-400">PICTURES</span>`:`<span>${txt}</span>`;i=(i+1)%tickerItems.length};paint();if(!matchMedia('(prefers-reduced-motion: reduce)').matches)setInterval(paint,3200)}
function renderProjects(filter='all'){const grid=$('#projectsGrid');const list=projects.filter(p=>filter==='all'||p.division===filter);$('#emptyState').classList.toggle('hidden',list.length>0);grid.innerHTML=list.map(p=>`<article class="card reveal overflow-hidden rounded-3xl border border-white/10 bg-white/[.035]" style="--accent:${p.color||'#18bdf2'}"><div class="relative aspect-[16/10] overflow-hidden bg-gradient-to-br from-white/10 to-black"><div class="absolute inset-0" style="background:radial-gradient(circle at 70% 30%, ${p.color||'#18bdf2'}33, transparent 40%)"></div>${p.image?`<img src="${p.image}" alt="Arte de ${esc(p.title)}" loading="lazy" class="relative w-full h-full object-cover"/>`:''}<div class="absolute inset-0 bg-gradient-to-t from-black/90 via-black/10 to-transparent"></div><div class="absolute left-5 right-5 bottom-5 flex items-end justify-between gap-4"><div><div class="text-[10px] font-black uppercase tracking-[.24em]" style="color:${p.color||'#18bdf2'}">UB. ${p.division==='animation'?'Animation':'Pictures'}</div><h3 class="mt-1 text-2xl font-black">${esc(p.title)}</h3></div><span class="text-xs text-white/50">${p.year||''}</span></div></div><div class="p-5 flex items-center justify-between gap-4"><p class="text-sm text-white/45 line-clamp-2">${esc(p.description||'')}</p><i data-lucide="arrow-up-right" class="shrink-0"></i></div></article>`).join('');lucide.createIcons();requestAnimationFrame(()=>document.querySelectorAll('.reveal').forEach(x=>observer.observe(x)));}
function esc(v=''){return v.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function loadProjects(){if(DEMO_MODE){projects=demoProjects;renderProjects();return}const {data,error}=await supabase.from('projects').select('*').eq('published',true).order('featured',{ascending:false}).order('created_at',{ascending:false});if(error){console.error(error);projects=[]}else projects=data||[];renderProjects()}
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.08});
function init(){lucide.createIcons();renderTicker();loadProjects();document.querySelectorAll('.reveal').forEach(x=>observer.observe(x));const header=$('#siteHeader');addEventListener('scroll',()=>{header.classList.toggle('bg-black/70',scrollY>30);header.classList.toggle('backdrop-blur-xl',scrollY>30);$('#progress').style.transform=`scaleX(${scrollY/(document.documentElement.scrollHeight-innerHeight)})`},{passive:true});$('#menuBtn').addEventListener('click',()=>{const open=$('#mobileMenu').classList.toggle('hidden');$('#menuBtn').setAttribute('aria-expanded',String(!open))});document.querySelectorAll('#mobileMenu a').forEach(a=>a.addEventListener('click',()=>$('#mobileMenu').classList.add('hidden')));document.querySelectorAll('.filterBtn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filterBtn').forEach(x=>x.classList.replace('bg-white','bg-white/5')||x.classList.remove('text-black'));b.classList.replace('bg-white/5','bg-white');b.classList.add('text-black');renderProjects(b.dataset.filter)}));}
init();
